### ISSUE TITLE
Precice 2.5.0 alters output of coupled_laplace_problem.

### ISSUE THREAD

**Issue by marcfehling** [dealii/code-gallery#135]
With the newest [precice 2.5.0 release](https://github.com/precice/precice/releases/), the output of the [coupled_laplace_problem](https://github.com/marcfehling/code-gallery/tree/master/coupled_laplace_problem) scenario changed. The code compiles, but the output differs.

This manifests in the CI failing when bumping the release version from 2.4.0 to 2.5.0. You can find the logs [here](https://github.com/marcfehling/code-gallery/actions/runs/4703108000).

@davidscn -- Can you have a look?

**Comment by davidscn** [comment]
Yes, thanks for the hint. I was considering to wait a bit longer and immediately upgrade to the upcoming precice v3, but updating is trivial, I will do it next week.

**Comment by marcfehling** [comment]
Waiting for the v3 release is fine with me. This is not critical.
