### ISSUE TITLE
`nonlinear-heat_transfer_with_AD_NOX`: needs an open source license

### ISSUE THREAD

**Issue by tamiko** [dealii/code-gallery#193]
@magomedovs Thanks a lot again for your code contribution. In order to properly integrate it into the code gallery we would need an open source license that applies to your code contribution. You can read more about it here: https://github.com/dealii/code-gallery/blob/master/LICENSE.md

We recommend that you publish your code under the same license terms that apply to deal.II, which is dual-licensed under
[<b>Apache License 2.0</b>](https://spdx.org/licenses/Apache-2.0.html) with [<b>LLVM Exception</b>](https://spdx.org/licenses/LLVM-exception.html) and the [<b>GNU Lesser General Public License v2.1 or later</b>](https://spdx.org/licenses/LGPL-2.1-or-later.html).

If you are OK with it then we would add the following license header to all source files:
```
/* -----------------------------------------------------------------------------
 *
 * SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR LGPL-2.1-or-later
 * Copyright (C) XXXX by <YOUR NAME>
 *
 * This file is part of the deal.II code gallery.
 *
 * -----------------------------------------------------------------------------
 */
```

**Comment by marcfehling** [comment]
@narasimhan-2604 -- _ping_

**Comment by tamiko** [comment]
@magomedovs Apologies, I have opened way too many issues/pull requests in the last 72h :sweat_smile:

**Comment by narasimhan-2604** [comment]
Sorry for the late response. Yes I am ok with this. Please go ahead.
