### ISSUE TITLE
update to latest deal.II release

### ISSUE THREAD

**Issue by tjhei** [dealii/code-gallery#66]
Many of the examples require older version of deal.II and no longer compile. I think it might be worth bumping the minimum version and updating at least to 9.1:
```
cdr/CMakeLists.txt:FIND_PACKAGE(deal.II 8.4 QUIET
CeresFE/CMakeLists.txt:FIND_PACKAGE(deal.II 8.3 QUIET
Distributed_LDG_Method/CMakeLists.txt:FIND_PACKAGE(deal.II 8.0 QUIET
ElastoplasticTorsion/CMakeLists.txt:FIND_PACKAGE(deal.II 8.0 QUIET
goal_oriented_elastoplasticity/CMakeLists.txt:FIND_PACKAGE(deal.II 8.0 QUIET
Linear_Elastic_Active_Skeletal_Muscle_Model/CMakeLists.txt:FIND_PACKAGE(deal.II 8.5 QUIET
MultipointFluxMixedFiniteElementMethods/CMakeLists.txt:FIND_PACKAGE(deal.II 9.0.0 QUIET
Quasi_static_Finite_strain_Compressible_Elasticity/CMakeLists.txt:FIND_PACKAGE(deal.II 8.5 QUIET
Quasi_static_Finite_strain_Quasi_incompressible_ViscoElasticity/CMakeLists.txt:FIND_PACKAGE(deal.II 8.5 QUIET
time_dependent_navier_stokes/CMakeLists.txt:FIND_PACKAGE(deal.II 9.0.0 QUIET
two_phase_flow/CMakeLists.txt:FIND_PACKAGE(deal.II 8.4 QUIET
```

**Comment by bangerth** [comment]
Yes. If things run with 9.2, we might as well require that.

**Comment by jppelteret** [comment]
I'd be happy with us checking that all of the codes run on the latest release, fixing any errors, and then just doing a version bump for all of them. We could always create a version tag so that people can still get the "old" versions of the code if they need to.

**Comment by jppelteret** [comment]
Please let me know what the ultimate decision is. #49 has been sitting around for an embarrassingly long time, so I plan on checking that, patching it if necessary and merging it before the release. I took a quick look at it yesterday and it all looks pretty neat and tidy.

**Comment by bangerth** [comment]
On 5/1/20 1:33 PM, Jean-Paul Pelteret wrote:
>  #49 
> <https://github.com/dealii/code-gallery/pull/49> has been sitting around for 
> an embarrassingly long time, so I plan on checking that, patching it if 
> necessary and merging it before the release. I took a quick look at it 
> yesterday and it all looks pretty neat and tidy.

That would be absolutely super. I would love to have that code reviewed. 
@jcc42 was in my class and I didn't want to review the code because I don't 
like reviewing my own students' codes. But I would have made that clear in the 
PR at the time :-(
