### ISSUE TITLE
Quasi-Static Finite-Strain Compressible Elasticity

### ISSUE THREAD

**Issue by Lianxiali** [dealii/code-gallery#89]
1.       The index should be 2 for z coordinate in make_grid()
          
               else if (std::abs(std::abs(cell->face(face)->center()[**0**]) - 0.5) < tol_boundary)
                  cell->face(face)->set_boundary_id(2); // +Z and -Z faces 
           
2.      In make_constraints(), the conditional statement seems not to work as the if block and else block are the same.

                  if (apply_dirichlet_bc == true)
                            block
                  else
                            same block

3.     In print_vertical_tip_displacement()， the following line triggers an error in case 3D and debug mode.

                  Point<dim> soln_pt (48.0*parameters.scale,60.0*parameters.scale);

**Comment by Lianxiali** [comment]
This paragraph regarding boundary conditions is confusing. The IDs are not consistent with the previous assignment when creating the grid.  In addtion, +X is traction prescribed not traction free. +Y and -Y are traction free.

> The boundary conditions for the indentation problem are as follows: On the -x, -y and -z faces (ID's 0,2,4) we set up a symmetry condition to allow only planar movement while the +x and +y faces (ID's 1,3) are traction free. In this contrived problem, part of the +z face (ID 5) is set to have no motion in the x- and y-component. Finally, as described earlier, the other part of the +z face has an the applied pressure but is also constrained in the x- and y-directions.

**Comment by marcfehling** [comment]
These all sound like important improvements for the code-gallery program! Would you be willing to open a pull request that implements your suggestions? If you need help on how to open a PR, you can find more information in the [wiki](https://github.com/dealii/dealii/wiki/Contributing).

@jppelteret -- FYI

**Comment by Lianxiali** [comment]
If you have confirmed all of them, I would be happy to pull a request.

**Comment by jppelteret** [comment]
These were fixed by #90 .
